SELECT * FROM STAND_USER;

-- QUESTION 1

SELECT AVG(POWER) AS "AVG_POWER", MAX(POWER) AS "MAX_POWER", MIN(POWER) AS "MIN_POWER"
FROM STAND_USER;

--QUESTION 2

SELECT COUNT(PRECISION) as "KNOWN_PRECISION", COUNT(*) as "TOTAL_USERS"
FROM STAND_USER;

--QUESTION 3

SELECT ROUND(stddev(power), 3) AS "STDDEV_POWER", ROUND(VARIANCE(power), 3) AS "VARIANCE_POWER"
FROM STAND_USER;

--QUESTION 4

SELECT PRECISION, AVG(POWER) AS "AVG_POWER"
FROM STAND_USER
WHERE PRECISION IS NOT NULL
GROUP BY PRECISION;

--QUESTION 5

SELECT PRECISION, AVG(POWER) AS "AVG_POWER"
FROM STAND_USER
WHERE PRECISION IS NOT NULL
HAVING AVG(POWER) > 80
GROUP BY PRECISION;

--QUESTION 6 (USED CHATGPT TO HELP)

SELECT USER_NAME, STAND_NAME, ROUND(POWER - (SELECT AVG(POWER) FROM STAND_USER), 3) AS "DIFF_FROM_AVG"
FROM STAND_USER;

--QUESTION 7

SELECT ROUND(AVG(POWER), 2) AS "ROUNDED_AVG_POWER"
FROM STAND_USER;

--QUESTION 8

SELECT PRECISION, SUM(POWER) AS "TOTAL_POWER"
FROM STAND_USER
GROUP BY ROLLUP(PRECISION);

--QUESTION 9

SELECT EXTRACT(YEAR FROM debut_date) AS debut_year,
       precision,
       SUM(power) AS total_power
FROM stand_user
GROUP BY CUBE(EXTRACT(YEAR FROM debut_date), precision)
ORDER BY debut_year, precision;
